### ISSUE TITLE
fail to compile

### ISSUE THREAD

**Issue by kiyoungkim1** [iamvucms/react-native-facebook-clone#1]
Thank you for your contibution!!

I got this message.
I dont`t know why some files cause this error!

> You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> 
> export default class extends Component {
>     static propTypes = {
>         shouldUpdate: PropTypes.bool.isRequired
>     };

thanks again!

**Comment by iamvucms** [comment]
Can you describe how did you run (commands)?

**Comment by kiyoungkim1** [comment]
> Can you describe how did you run (commands)?

just as you wrote in README.md.
I remove some import lines in App.js then it works well as you showed in youtube. (Youtube clip is really helpful cause I can check what this application can do)

I figure out those import lines by removing one by one. when I remove these lines it works well:
import PostOptions from './screens/PostOptions'
import ProfilePostOptions from './screens/ProfileTab/ProfilePostOptions'
import WatchOptions from './screens/WatchTab/WatchOptions'
import ProfilePostOptions from './screens/ProfileTab/ProfilePostOptions'
import FriendOptions from './screens/ProfileTab/FriendOptions'
import AvatarOptions from './screens/ProfileTab/AvatarOptions'

I use Ubuntu18.04.
I will check it again cause I have not closely looked codes.

thanks again.

**Comment by kiyoungkim1** [comment]
Also, to run the code, I changed 
group.js --> Group.js in 'react-native-facebook-clone/screens/GroupTab/'

**Comment by iamvucms** [comment]
Hi, 
I'm sorry about this, you can try demo at https://expo.io/@vucms/First.
This is my first react native app, It still has a lot of bugs. I just tested on IOS so Android maybe not working well.
If you interested in App clone, try my newest Instagram deep clone with firebase and react native.
Thanks!!!
