### ISSUE TITLE
Module not found: Can't resolve './screens/GroupTab/Group' in ./App.js:58

### ISSUE THREAD

**Issue by maulik41** [iamvucms/react-native-facebook-clone#23]
![Screenshot from 2021-11-15 18-10-29](https://user-images.githubusercontent.com/44226986/141783843-eeb0d748-1f34-4a9a-8aaa-0b2e4357bc54.png)

**Comment by iamvucms** [comment]
Hi, I didn't build this project for web platform.

**Comment by maulik41** [comment]
@iamvucms ok, thanks for your reply
