### ISSUE TITLE
Unable to start the project

### ISSUE THREAD

**Issue by jb29611** [iamvucms/react-native-facebook-clone#3]
Hello,
I hope you are fine.

I did as said in the readme file. 
installed json server, packages.

1) Yarn start

Expo DevTools is running at http://localhost:19002
Starting Metro Bundler on port 19001.
Your native app is running at expcc3b74abcde84bd495f8a48a272d9252://192.168.86.20:19000
Logs for your project will appear below. Press Ctrl+C to exit.

localhost 19002 -> Scanned the QR code and I'm getting No usable data found notification from expo.

Can you please help me?

**Comment by iamvucms** [comment]
Hi,
Can you capture screen?
Is this my app error or expo client error ?
My expo demo: [https://expo.io/@vucms/First](https://expo.io/@vucms/First)

**Comment by jb29611** [comment]
Hello,

![rn_fb](https://user-images.githubusercontent.com/36976196/88536750-fd4add80-d029-11ea-8bca-3ec28ded00a1.gif)

After Scanning I get this notification
![no_data](https://user-images.githubusercontent.com/36976196/88536800-0d62bd00-d02a-11ea-8736-ce5daae6e4bb.jpg)


I tried accessing via your demo link and I'm getting an error.
![rn_error](https://user-images.githubusercontent.com/36976196/88536859-210e2380-d02a-11ea-9a97-63bc638252be.jpg)

Thanks for your time. :)

**Comment by jb29611** [comment]
Hello,

![rn_fb](https://user-images.githubusercontent.com/36976196/88537216-c923ec80-d02a-11ea-803e-2c989b184396.gif)

After Scanning I get this notification
![no_data](https://user-images.githubusercontent.com/36976196/88536800-0d62bd00-d02a-11ea-8736-ce5daae6e4bb.jpg)


I tried accessing via your demo link and I'm getting an error.
![rn_error](https://user-images.githubusercontent.com/36976196/88536859-210e2380-d02a-11ea-9a97-63bc638252be.jpg)

Thanks for your time. :)

**Comment by jb29611** [comment]
Hello,

![rn_fb](https://user-images.githubusercontent.com/36976196/88536750-fd4add80-d029-11ea-8bca-3ec28ded00a1.gif)

After Scanning I get this notification
![no_data](https://user-images.githubusercontent.com/36976196/88536800-0d62bd00-d02a-11ea-8736-ce5daae6e4bb.jpg)


I tried accessing via your demo link and I'm getting an error.
![rn_error](https://user-images.githubusercontent.com/36976196/88536859-210e2380-d02a-11ea-9a97-63bc638252be.jpg)

Thanks for your time. :)

**Comment by iamvucms** [comment]
Hi, 
I think the problem come from your expo client app.
![image](https://user-images.githubusercontent.com/17398401/88537367-a77d3200-d037-11ea-9a35-3c4229dec470.png
Do you try it on another phone.
~~

**Comment by jb29611** [comment]
Hello,

I tried opening with IOS device, maybe that is why I was getting an error while opening your demo expo.
Is there a link for IOS device? 
And after trying for quite sometime I'm still unable to open the cloned repository. Is there something that I am missing?

**Comment by iamvucms** [comment]
Hmm,
A sad story that I don't have real iOS device to test, just be on iOS simulator.
Maybe It's a issue on IOS expo client.

**Comment by jb29611** [comment]
I tried opening your demo app using https://expo.io/appetize-simulator?url=https://expo.io/@vucms/First and it works fine.

Unfortunately unable to run the project in my local device :(

**Comment by iamvucms** [comment]
What don't you run it on simulator ?

**Comment by jb29611** [comment]
I'm unable to run the project on my machine to run it on the simulator. 
Whenever I try to run the project and scan it using the expo explorer I get no usable data notification from expo. 
I'm still trying to open the project but failed until now.

**Comment by iamvucms** [comment]
> I'm unable to run the project on my machine to run it on the simulator.
> Whenever I try to run the project and scan it using the expo explorer I get no usable data notification from expo.
> I'm still trying to open the project but failed until now.

Sorry about it. I no longer maintain it when focusing to Instagram Clone.
Try to use another phone. The problem is your expo client app.
Have a nice day !!!
