### ISSUE TITLE
Error startup-running in local web browser in expo

### ISSUE THREAD

**Issue by venkatamandala** [iamvucms/react-native-facebook-clone#4]
Hello, i am getting below error on startup 

web  Failed to compile.

/react-native-facebook-clone-master/node_modules/static-container/StaticContainer.js 5:21
Module parse failed: Unexpected token (5:21)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| 
| export default class extends Component {
>     static propTypes = {
|         shouldUpdate: PropTypes.bool.isRequired
|     };

![image](https://user-images.githubusercontent.com/37226072/91276501-408e8e00-e747-11ea-8d52-7d907d947919.png)

![image](https://user-images.githubusercontent.com/37226072/91276617-674cc480-e747-11ea-87cb-bdc3bc02b3b9.png)

**Comment by iamvucms** [comment]
Hey, sorry but I still didn't try to run on web. My developement enviroment just be on IOS.
