### ISSUE TITLE
Could not read script 'E:\Android Projects\react-native-facebook-clone-master\node_modules\react-native-unimodules\gradle.groovy' as it does not exist. Open File

### ISSUE THREAD

**Issue by adetheprince** [iamvucms/react-native-facebook-clone#5]
Could not read script 'E:\Android Projects\react-native-facebook-clone-master\node_modules\react-native-unimodules\gradle.groovy' as it does not exist.
Open File

**Comment by iamvucms** [comment]
Hey bro, try to npm install --save or yarn and then continue to fix. 
You also can try live demo before  https://expo.io/@vucms/First
Good luck

**Comment by adetheprince** [comment]
Hi there thanks for reply 😃
I have tried to open the project using Android studio to test it on Android
but AS gives me that error I am not sure how to open react native project
with android studio. Is there anything else I need to do or how can I use
install npm on Android studio

**Comment by iamvucms** [comment]
Hey. expo project may be difficult to run on Android studio/Xcode like react-native cli. 
If you are intertered in my clone apps try this clone https://github.com/iamvucms/react-native-instagram-clone (react-native cli).
If you want run npm install. try to use cd command to your project path and run npm install.
