### ISSUE TITLE
Install

### ISSUE THREAD

**Issue by Krishna8077078** [iamvucms/react-native-facebook-clone#9]
How To Install And run in android

**Comment by iamvucms** [comment]
Hi, you need to install expo cli on your pc then clone this project and follow the readme guide. Good luck

**Comment by ultra-pool** [comment]
`npm install expo-cli --global`
Might also need to use sudo depending on your OS and setup. I use Ubuntu OS's only on servers and home PC's.
Also youll need to have all the android files installed and synced into the source using Android Studio.
